
import { HanziData } from './types';

export const HANZI_DATABASE: HanziData[] = [
  { "simplified" : "阿拉伯语",
    "radical"    : "阝",
    "level"      : [ "new-7" ],
    "frequency"  : 27202,
    "pos"        : [ "nz" ],
    "forms"      : [ { "traditional"    : "阿拉伯語",
                       "transcriptions" : { "pinyin"    : "Ā lā bó yǔ",
                                            "numeric"   : "A1 la1 bo2 yu3",
                                            "wadegiles" : "a¹ la¹ po² yü³",
                                            "bopomofo"  : "ㄚ ㄌㄚ ㄅㄛˊ ㄩˇ",
                                            "romatzyh"  : "a lha bor yeu" },
                       "meanings"       : [ "Arabic (language)" ],
                       "classifiers"    : [] } ] },
  { "simplified" : "阿姨",
    "radical"    : "阝",
    "level"      : [ "new-4", "old-3" ],
    "frequency"  : 4355,
    "pos"        : [ "n" ],
    "forms"      : [ { "traditional"    : "阿姨",
                       "transcriptions" : { "pinyin"    : "ā yí",
                                            "numeric"   : "a1 yi2",
                                            "wadegiles" : "a¹ i²",
                                            "bopomofo"  : "ㄚ ㄧˊ",
                                            "romatzyh"  : "a yi" },
                       "meanings"       : [ "maternal aunt",
                                            "step-mother",
                                            "childcare worker",
                                            "nursemaid",
                                            "woman of similar age to one's parents (term of address used by child)" ],
                       "classifiers"    : [ "个" ] } ] },
  { "simplified" : "呵",
    "radical"    : "口",
    "level"      : [ "old-6" ],
    "frequency"  : 5230,
    "pos"        : [ "y", "e", "v" ],
    "forms"      : [ { "traditional"    : "呵",
                       "transcriptions" : { "pinyin"    : "ā",
                                            "numeric"   : "a1",
                                            "wadegiles" : "a¹",
                                            "bopomofo"  : "ㄚ",
                                            "romatzyh"  : "a" },
                       "meanings"       : [ "variant of 啊" ],
                       "classifiers"    : [] },
                     { "traditional"    : "呵",
                       "transcriptions" : { "pinyin"    : "hē",
                                            "numeric"   : "he1",
                                            "wadegiles" : "ho¹",
                                            "bopomofo"  : "ㄏㄜ",
                                            "romatzyh"  : "he" },
                       "meanings"       : [ "expel breath", "my goodness" ],
                       "classifiers"    : [] } ] },
  { "simplified" : "呵护",
    "radical"    : "口",
    "level"      : [ "new-7" ],
    "frequency"  : 13381,
    "pos"        : [ "v", "vn" ],
    "forms"      : [ { "traditional"    : "呵護",
                       "transcriptions" : { "pinyin"    : "hē hù",
                                            "numeric"   : "he1 hu4",
                                            "wadegiles" : "ho¹ hu⁴",
                                            "bopomofo"  : "ㄏㄜ ㄏㄨˋ",
                                            "romatzyh"  : "he huh" },
                       "meanings"       : [ "to bless",
                                            "to cherish",
                                            "to take good care of",
                                            "to conserve" ],
                       "classifiers"    : [] } ] },
  { "simplified" : "安宁",
    "radical"    : "宀",
    "level"      : [ "new-7", "old-5" ],
    "frequency"  : 9001,
    "pos"        : [ "adj", "n" ],
    "forms"      : [ { "traditional"    : "安寧",
                       "transcriptions" : { "pinyin"    : "ān níng",
                                            "numeric"   : "an1 ning2",
                                            "wadegiles" : "an¹ ning²",
                                            "bopomofo"  : "ㄢ ㄋㄧㄥˊ",
                                            "romatzyh"  : "an ning" },
                       "meanings"       : [ "peaceful", "tranquil", "calm", "peace" ],
                       "classifiers"    : [] } ] },
  { "simplified" : "安心",
    "radical"    : "宀",
    "level"      : [ "new-5", "old-4" ],
    "frequency"  : 7500,
    "pos"        : [ "v", "adj" ],
    "forms"      : [ { "traditional"    : "安心",
                       "transcriptions" : { "pinyin"    : "ān xīn",
                                            "numeric"   : "an1 xin1",
                                            "wadegiles" : "an¹ hsin¹",
                                            "bopomofo"  : "ㄢ ㄒㄧㄣ",
                                            "romatzyh"  : "an shin" },
                       "meanings"       : [ "to feel at ease", "to be relieved", "to focus one's mind" ],
                       "classifiers"    : [] } ] },
  { "simplified" : "爸爸",
    "radical"    : "父",
    "level"      : [ "new-1", "old-1" ],
    "frequency"  : 500,
    "pos"        : [ "n" ],
    "forms"      : [ { "traditional"    : "爸爸",
                       "transcriptions" : { "pinyin"    : "bà ba",
                                            "numeric"   : "ba4 ba",
                                            "wadegiles" : "pa⁴ pa",
                                            "bopomofo"  : "ㄅㄚˋ ㄅㄚ",
                                            "romatzyh"  : "bah ba" },
                       "meanings"       : [ "dad", "father" ],
                       "classifiers"    : [ "个" ] } ] },
  { "simplified" : "明白",
    "radical"    : "日",
    "level"      : [ "new-2", "old-2" ],
    "frequency"  : 1200,
    "pos"        : [ "v", "adj" ],
    "forms"      : [ { "traditional"    : "明白",
                       "transcriptions" : { "pinyin"    : "míng bai",
                                            "numeric"   : "ming2 bai",
                                            "wadegiles" : "ming² pai",
                                            "bopomofo"  : "ㄇㄧㄥˊ ㄅㄞ˙",
                                            "romatzyh"  : "ming bai" },
                       "meanings"       : [ "to understand", "clear", "obvious" ],
                       "classifiers"    : [] } ] }
];
